deploy:
  provider: rubygems
  api_key:
    secure: KRgSlJX3GzkutICLZ6zuPi1NovQ5w6b3+BnKVSpUdBRYPrKFAWu8Ym1CEuiOp6QXBr8wfTon9LQcPejD7wIC3kEPuVvRXTRd3sJ+rVkBuhkiGovBqrJRHKY695XlGN2agn9Shk9Al6vPJM8tK2w5pXgLBt5A4nn/SwuAam1KfhBgSRuxn/QBI0y20JYNhSbGFRgwUgnynTAqf6oEHdeDn4P0l2I2YIiUXaMvpLntk8KAdQziuihCPdrTOKrtk9WRryh6bh3N/wRuG28AbTUZ54cv3sbsLKtQKehOxEJYecjBDzD7Oklyn63zKNROsIsEcQRIsOhIhqSwx9gjpDUJHRpdvrzYZ8Rrb/I03IG2XCoFncPzCgu4icV2JFTsfrmflDCUgOg77yxhbCDE9uV+RPks/RAd9Tc8oTtbUj9HFh/iV20UPZ8xXGof2/eqmw7ETLcmL/O/6Hi1hsKVfz+KuIGtncHXrAc61ns0RBmbzoz5zbSRy1uDTwGtNQsakJ3ggHHGiW5bYmiNOfDlOkzIA64F7WFZRIPShkp3fRIhmxYeNuqITcbOyZI7ZFkvMGoHQDjvhFtd5tTiTpGHdGkNXQC/g0CDJ22IlpkmqMRKdBpYMGwKsPdQheuxjgLDmn1I4R7zt4NnMSk55CmdR/mDWfAeLTo+pBKAtM8tPo2bEVI=
  gemspec: xsrb.gemspec
  on:
    tags: true
